--
-- ninja.lua
-- Common functions for writing Ninja build files.
-- (c) 2025 Nick Clark and the Premake project
--

	local p = premake

	p.modules.ninja = {}
	p.modules.ninja._VERSION = "0.0.1"

	local ninja = p.modules.ninja

--
-- Generates a header for a workspace or project.
--
-- @param tgt
--    The workspace or project object.
--
	function ninja.header(tgt)
		local kind = iif(tgt.project, "project", "workspace")
		_p('# %s %s Ninja build file autogenerated by Premake', tgt.name, kind)
		_p('')
	end

--
-- Escapes a string for use in a Ninja build file. Ninja uses $ as an escape. See https://ninja-build.org/manual.html#ref_lexer
--
-- @param value
--    The string to be escaped.
-- @return
--    The escaped string.
--
	function ninja.esc(value)
		value = value:gsub("%$", "$$") -- $ -> $$
		value = value:gsub(":", "$:") -- : -> $:
		value = value:gsub("\n", "$\n") -- \n -> $\n
		value = value:gsub(" ", "$ ") -- space -> $space
		return value
	end

	return ninja
