--
-- test_ninja.lua
-- Test the common ninja functions
-- (c) 2025 Nick Clark and the Premake project
--

	local p = premake
	local suite = test.declare("ninja_common")

	local wks, prj

--
-- Setup
--

	function suite.setup()
		wks = test.createWorkspace()
		prj = p.workspace.getproject(wks, 1)
	end

--
-- Ensure the header contains the workspace name.
--

	function suite.header_onWorkspace()
		ninja.header(wks)
		test.capture [[
# MyWorkspace workspace Ninja build file autogenerated by Premake
]]
	end


--
-- Ensure the header contains the project name.
--

	function suite.header_onProject()
		ninja.header(prj)
		test.capture [[
# MyProject project Ninja build file autogenerated by Premake
]]
	end
	

--
-- Test escaping strings for use in Ninja build files.
--

	function suite.esc()
		test.isequal("foo", ninja.esc("foo"))
		test.isequal("foo$$bar", ninja.esc("foo$bar"))
		test.isequal("foo$:bar", ninja.esc("foo:bar"))
		test.isequal("foo$\nbar", ninja.esc("foo\nbar"))
		test.isequal("foo$ bar", ninja.esc("foo bar"))

		-- Test multiple replacements
		test.isequal("foo$$bar$:baz$\nqux", ninja.esc("foo$bar:baz\nqux"))
	end